name: yaml-formatter
on:
  push:
    branches: [develop, feature/*, bugfix/*, hotfix/*]
  pull_request:
    branches: [develop]
permissions:
  contents: write
jobs:
  formatter_name:
    name: runner / yamlfix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.THERMOSTATSUPERVISOR_PR }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install yamlfix
        run: |
          python -m pip install --upgrade pip
          pip install yamlfix
      - name: Check files using yamlfix
        id: yamlfix_check
        run: |
          if yamlfix --check .; then
            echo "is_formatted=false" >> $GITHUB_OUTPUT
          else
            echo "is_formatted=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true
      - name: Format files with yamlfix
        if: steps.yamlfix_check.outputs.is_formatted == 'true'
        run: |
          yamlfix .
      - name: Commit changes
        if: steps.yamlfix_check.outputs.is_formatted == 'true'
        run: |-
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":art: Format YAML files with yamlfix"
          git push origin HEAD:${{ github.head_ref || github.ref_name }}
